import React, { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const model = window.__SPEC_DOCK__;
const erSource = window.__SPEC_DOCK_ER__;
const iconPaths = { grid: "<rect x='3' y='3' width='7' height='7' rx='1'/><rect x='14' y='3' width='7' height='7' rx='1'/><rect x='3' y='14' width='7' height='7' rx='1'/><rect x='14' y='14' width='7' height='7' rx='1'/>", doc: "<path d='M6 3h8l4 4v14H6z'/><path d='M14 3v5h5M9 13h6M9 17h6'/>", api: "<path d='M5 5h5v5H5zM14 14h5v5h-5zM10 7h4a2 2 0 0 1 2 2v5M7.5 10v3a2 2 0 0 0 2 2H14'/>", db: "<ellipse cx='12' cy='5.5' rx='7.5' ry='3'/><path d='M4.5 5.5v6c0 1.7 3.4 3 7.5 3s7.5-1.3 7.5-3v-6M4.5 11.5v6c0 1.7 3.4 3 7.5 3s7.5-1.3 7.5-3v-6'/>", split: "<path d='M12 3v18M3 6h6M3 12h6M3 18h6M15 6h6M15 12h6M15 18h6'/>", panel: "<path d='M4 5h16v14H4zM4 9h16M9 9v10'/>", panelLeft: "<path d='M4 5h16v14H4zM9 5v14'/>", eye: "<path d='M2.5 12s3.5-5 9.5-5 9.5 5 9.5 5-3.5 5-9.5 5-9.5-5-9.5-5z'/><circle cx='12' cy='12' r='2.5'/>", code: "<path d='M8 5l-6 7 6 7M16 5l6 7-6 7M14 3l-4 18/>" };
const esc = (value) => String(value ?? "").replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
function Icon({ name }) { return <svg className="icon" viewBox="0 0 24 24" dangerouslySetInnerHTML={{ __html: iconPaths[name] || iconPaths.grid }} />; }
function parseRoute(route) { const [view, id] = route.split("/"); return { view, id }; }
function titleOf(route) { const { view, id } = parseRoute(route); if (view === "overview") return "概要"; if (view === "er") return "ER図"; if (view === "api") return id ? `${model.openapi.operations[Number(id)]?.method} ${model.openapi.operations[Number(id)]?.path}` : "API"; if (view === "database") return id ? model.prisma.models[Number(id)]?.name : "Database"; if (view === "zod") return id ? model.zod.schemas[Number(id)]?.name : "Zod"; return model.markdown.documents[Number(id)]?.title || "Document"; }
function Table({ headers, rows, empty = "データはありません" }) { return rows.length ? <table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows}</tbody></table> : <p className="empty">{empty}</p>; }
function schemaType(schema) { if (!schema) return ""; if (schema.type === "array") return `${schemaType(schema.items)}[]`; return schema.ref || schema.name || schema.type || "object"; }
function schemaConstraint(schema) { return [schema.format, schema.enum?.length ? `enum: ${schema.enum.join(", ")}` : "", schema.minimum != null ? `最小 ${schema.minimum}` : "", schema.maximum != null ? `最大 ${schema.maximum}` : "", schema.minLength != null ? `最小文字数 ${schema.minLength}` : "", schema.maxLength != null ? `最大文字数 ${schema.maxLength}` : "", schema.minItems != null ? `最小件数 ${schema.minItems}` : "", schema.maxItems != null ? `最大件数 ${schema.maxItems}` : "", schema.default != null ? `既定値 ${schema.default}` : ""].filter(Boolean).join(" / "); }
function schemaRows(schema, prefix = "") { if (!schema) return []; const rows = []; const add = (value, name, required, path) => { const currentPath = path ? `${path}.${name}` : name; rows.push(<tr key={currentPath}><td><code>{currentPath}</code></td><td><code>{schemaType(value)}</code></td><td>{required ? "必須" : "任意"}</td><td>{schemaConstraint(value)}</td><td>{value.description || ""}</td></tr>); if (value.properties) rows.push(...schemaRows(value, currentPath)); if (value.items?.properties) rows.push(...schemaRows(value.items, `${currentPath}[]`)); }; if (schema.allOf) schema.allOf.forEach((part) => rows.push(...schemaRows(part, prefix))); Object.entries(schema.properties || {}).forEach(([name, value]) => add(value, name, schema.required?.includes(name), prefix)); return rows; }
function SchemaTable({ schema }) { return <Table headers={["項目", "型", "必須", "制約", "説明"]} rows={schemaRows(schema)} empty="スキーマ定義はありません。"/>; }
function securityLabel(security) { if (!security?.length) return "認証なし"; return security.map((item) => { const scheme = item.scheme; if (scheme?.type === "http") return `${scheme.scheme === "bearer" ? "Bearer" : scheme.scheme} ${scheme.bearerFormat ? `(${scheme.bearerFormat})` : ""}`.trim(); if (scheme?.type === "apiKey") return `${scheme.name} (${scheme.in})`; return item.name; }).join(" / "); }
function Head({ eyebrow, title, description }) { return <header className="page-header"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></header>; }
function Overview({ open }) { const items = [["api", "API一覧", model.openapi.operations.length], ["database", "Database", model.prisma.models.length], ["zod", "Zodスキーマ", model.zod.schemas.length], ["document", "Documents", model.markdown.documents.length]]; return <><section className="hero"><span className="eyebrow">仕様ワークスペース</span><h1>ソース仕様を理解する。</h1><p>Prisma、Zod、OpenAPI、Markdownを一つの場所で確認できます。</p></section><div className="stats">{items.map(([route, label, count]) => <button className="stat" key={route} onClick={() => open(route)}><strong>{count}</strong><span>{label}</span></button>)}</div><section className="panel"><h2>プロジェクトのソース</h2><div className="source-list">{[...model.prisma.files, ...model.openapi.files, ...model.zod.files, ...model.markdown.files].map((file) => <code key={file}>{file}</code>)}</div></section></>; }
function ApiPage({ id }) { if (id == null) return <><Head eyebrow="INTERFACE" title="API一覧" description="APIの入出力と制約を確認します。" /><p className="empty">サイドバーからAPIを選択してください。</p></>; const item = model.openapi.operations[Number(id)]; const responseHeaders = (item.responses || []).flatMap((response) => (response.headers || []).map((header) => ({ ...header, status: response.status }))); return <><Head eyebrow="API DETAIL" title={`${item.method} ${item.path}`} description={item.summary || item.operationId} /><section className="panel api-contract"><h2>API概要</h2><div className="contract-grid"><div><span>認証方式</span><strong>{securityLabel(item.security)}</strong></div><div><span>サーバー</span><strong>{item.servers?.[0]?.url || "定義なし"}</strong></div><div><span>操作ID</span><strong>{item.operationId || "定義なし"}</strong></div></div></section><section className="panel"><h2>パラメータ / ヘッダー</h2><Table headers={["名前", "場所", "型", "必須", "説明"]} rows={(item.parameters || []).map((p) => <tr key={`${p.in}-${p.name}`}><td><code>{p.name}</code></td><td>{p.in}</td><td>{p.schema?.type || p.schema?.ref || ""}</td><td>{p.required ? "必須" : "任意"}</td><td>{p.description || ""}</td></tr>)} empty="パラメータとヘッダーはありません。" /></section>{item.requestBody && <section className="panel request-body"><div className="section-heading"><h2>リクエストボディ</h2><span className={item.requestBody.required ? "required-badge" : "optional-badge"}>{item.requestBody.required ? "必須" : "任意"}</span></div><div className="schema-meta">{(item.requestBody.contentTypes || [item.requestBody.contentType || "application/json"]).map((type) => <code key={type}>{type}</code>)}{item.requestBody.schema?.ref && <code>{item.requestBody.schema.ref}</code>}</div>{item.requestBody.description && <p className="muted">{item.requestBody.description}</p>}<SchemaTable schema={item.requestBody.schema}/></section>}<section className="panel"><h2>レスポンス</h2><Table headers={["Status", "説明", "Content-Type", "スキーマ"]} rows={(item.responses || []).map((r) => <tr key={r.status}><td>{r.status}</td><td>{r.description}</td><td>{(r.contentTypes || []).join(", ") || "—"}</td><td>{r.schema?.ref || r.schema?.type || "—"}</td></tr>)}/>{responseHeaders.length > 0 && <><h3>Response headers</h3><Table headers={["Status", "Header", "型", "必須", "説明"]} rows={responseHeaders.map((header) => <tr key={`${header.status}-${header.name}`}><td>{header.status}</td><td><code>{header.name}</code></td><td>{header.schema?.type || header.schema?.ref || ""}</td><td>{header.required ? "必須" : "任意"}</td><td>{header.description || ""}</td></tr>)}/></>}</section></>; }
function DatabasePage({ id }) { if (id == null) return <><Head eyebrow="DATABASE" title="Database" description="モデル、インデックス、制約、リレーションを確認します。" /><p className="empty">サイドバーからモデルを選択してください。</p></>; const item = model.prisma.models[Number(id)]; return <><Head eyebrow="DATABASE DETAIL" title={item.name} description={item.description} /><section className="panel"><h2>フィールド</h2><Table headers={["名前", "型", "属性", "説明"]} rows={item.fields.map((f) => <tr key={f.name}><td><code>{f.name}</code></td><td>{f.type}{f.isArray ? "[]" : ""}{f.isOptional ? "?" : ""}</td><td>{[f.isId && "PK", f.isUnique && "UK", f.dbType].filter(Boolean).join(" / ")}</td><td>{f.description}</td></tr>)}/></section><section className="panel"><h2>インデックス・制約</h2><Table headers={["種類", "フィールド", "名前"]} rows={(item.constraints || []).map((c) => <tr key={c.name || c.fields.join(",")}><td>{c.kind}</td><td>{c.fields.join(", ")}</td><td>{c.name || ""}</td></tr>)} empty="モデル制約はありません。"/></section></>; }
function ZodPage({ id }) { if (id == null) return <><Head eyebrow="VALIDATION" title="Zodバリデーション" description="実行時バリデーションのスキーマを確認します。" /><p className="empty">サイドバーからスキーマを選択してください。</p></>; const item = model.zod.schemas[Number(id)]; return <><Head eyebrow="VALIDATION DETAIL" title={item.name} description={item.file}/><Table headers={["項目", "Zod型", "説明"]} rows={item.fields.map((field) => <tr key={field.name}><td><code>{field.name}</code></td><td>{field.type}</td><td>{field.description}</td></tr>)}/></>; }
function InlineMarkdown({ text }) { const parts = String(text).split(/(\*\*[^*]+\*\*|`[^`]+`|\[[^\]]+\]\([^\)]+\))/g).filter(Boolean); return <>{parts.map((part, index) => { if (part.startsWith("**") && part.endsWith("**")) return <strong key={index}>{part.slice(2, -2)}</strong>; if (part.startsWith("`") && part.endsWith("`")) return <code key={index}>{part.slice(1, -1)}</code>; const link = part.match(/^\[([^\]]+)\]\(([^\)]+)\)$/); if (link) return <a key={index} href={link[2]}>{link[1]}</a>; return <React.Fragment key={index}>{part}</React.Fragment>; })}</>; }
function MermaidBlock({ source }) { const ref = useRef(null); useEffect(() => { let cancelled = false; const render = () => { if (cancelled || !window.mermaid || !ref.current) return; window.mermaid.initialize({ startOnLoad: false, theme: "dark", securityLevel: "strict" }); window.mermaid.run({ nodes: [ref.current] }); }; if (window.mermaid) render(); else { const existing = document.querySelector('script[data-mermaid="true"]'); const script = existing || document.createElement("script"); script.src = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"; script.dataset.mermaid = "true"; script.addEventListener("load", render, { once: true }); if (!existing) document.head.appendChild(script); } return () => { cancelled = true; }; }, [source]); return <div className="doc-mermaid"><div ref={ref} className="mermaid">{source}</div></div>; }
function MarkdownView({ content }) { const lines = String(content || "").split("\n"); const blocks = []; let paragraph = []; let list = []; let code = null; const flushParagraph = () => { if (paragraph.length) { blocks.push({ type: "paragraph", lines: paragraph }); paragraph = []; } }; const flushList = () => { if (list.length) { blocks.push({ type: "list", lines: list }); list = []; } }; lines.forEach((line) => { const fence = line.match(/^```(.*)$/); if (fence) { if (code) { blocks.push({ type: code.language === "mermaid" ? "mermaid" : "code", language: code.language, lines: code.lines }); code = null; } else { flushParagraph(); flushList(); code = { language: fence[1].trim().toLowerCase(), lines: [] }; } return; } if (code) { code.lines.push(line); return; } const heading = line.match(/^(#{1,6})\s+(.+)$/); if (heading) { flushParagraph(); flushList(); blocks.push({ type: "heading", level: heading[1].length, text: heading[2] }); return; } const item = line.match(/^\s*[-*+]\s+(.+)$/); if (item) { flushParagraph(); list.push(item[1]); return; } if (!line.trim()) { flushParagraph(); flushList(); return; } paragraph.push(line); }); if (code) blocks.push({ type: "code", language: code.language, lines: code.lines }); flushParagraph(); flushList(); return <>{blocks.map((block, index) => { if (block.type === "heading") { const Heading = `h${block.level}`; return <Heading key={index}><InlineMarkdown text={block.text}/></Heading>; } if (block.type === "list") return <ul key={index}>{block.lines.map((line) => <li key={line}><InlineMarkdown text={line}/></li>)}</ul>; if (block.type === "mermaid") return <MermaidBlock key={index} source={block.lines.join("\n")}/>; if (block.type === "code") return <pre className="doc-fenced-code" key={index}><code>{block.lines.join("\n")}</code></pre>; return <p key={index}><InlineMarkdown text={block.lines.join("\n")}/></p>; })}</>; }
function DocumentPage({ id }) { const item = model.markdown.documents[Number(id)]; const [mode, setMode] = useState("view"); return <><Head eyebrow="DOCUMENT" title={item.title} description={item.summary}/><div className="document-toolbar"><code>{item.file}</code><div className="document-mode-actions"><button className={mode === "view" ? "active" : ""} onClick={() => setMode("view")}><Icon name="eye"/>表示</button><button className={mode === "code" ? "active" : ""} onClick={() => setMode("code")}><Icon name="code"/>Code</button></div></div><section className="panel">{mode === "view" ? <div className="doc-view"><MarkdownView content={item.body || item.content}/></div> : <pre className="doc-code">{item.content}</pre>}</section></>; }
function ErPage() { const [scale, setScale] = useState(1); useEffect(() => { const load = () => { window.mermaid.initialize({ startOnLoad: false, theme: "dark" }); window.mermaid.run({ nodes: [document.querySelector(".er-mermaid")] }); }; if (window.mermaid) load(); else { const script = document.createElement("script"); script.src = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"; script.onload = load; document.head.appendChild(script); } }, []); return <section className="er-workspace"><header className="er-header"><div><span className="eyebrow">RELATIONSHIPS</span><h1>ER図</h1><p>Prismaのモデルとリレーションを視覚的に確認します。</p></div><div className="er-tools"><button onClick={() => setScale(1)}>全体表示</button><button onClick={() => setScale((v) => Math.min(2.5, v + .15))}>＋</button><button onClick={() => setScale((v) => Math.max(.35, v - .15))}>−</button></div></header><div className="er-viewport"><div className="er-mermaid" style={{ transform: `scale(${scale})` }}>{erSource}</div></div></section>; }
function ActivityRail({ route, open, toggleExplorer, explorerOpen }) { return <aside className="activity-rail">{[["overview", "grid"], ["documents", "doc"], ["api", "api"], ["database", "db"]].map(([target, name], index) => <button className={`${route === target || route.startsWith(`${target}/`) ? "active" : ""} ${index === 0 && explorerOpen ? "panel-open" : ""}`} title={index === 0 ? "Explorerを表示/非表示" : target} key={target} onClick={() => { if (index === 0) toggleExplorer(); else { if (!explorerOpen) toggleExplorer(); open(target); } }}><Icon name={name}/></button>)}</aside>; }
function Explorer({ route, open, onResizeStart, onClose }) { const [query, setQuery] = useState(""); const match = (item) => !query || `${item.label} ${item.meta}`.toLowerCase().includes(query.toLowerCase()); const group = (title, name, values) => <details open><summary><Icon name={name}/>{title}<span>{values.length}</span></summary>{values.filter(match).map((item) => <button className={route === item.href ? "selected" : ""} key={item.href} onClick={() => open(item.href)}><strong>{item.label}</strong><small>{item.meta}</small></button>)}</details>; return <aside className="explorer"><div className="brand"><span>SpecDock<small>ソース仕様に接続する開発Studio</small></span><button className="explorer-close" title="Explorerを閉じる" aria-label="Explorerを閉じる" onClick={onClose}><Icon name="panelLeft"/></button></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="仕様を検索..."/><h2>エクスプローラー</h2><button className={route === "overview" ? "selected overview-link" : "overview-link"} onClick={() => open("overview")}><Icon name="grid"/>概要</button>{group("Documents", "doc", model.markdown.documents.map((x, i) => ({ href: `document/${i}`, label: x.title, meta: x.relatedOperations?.[0] || x.file })))}{group("API", "api", model.openapi.operations.map((x, i) => ({ href: `api/${i}`, label: `${x.method} ${x.path}`, meta: x.summary || x.operationId || "API操作" })))}{group("Zodバリデーション", "api", model.zod.schemas.map((x, i) => ({ href: `zod/${i}`, label: x.name, meta: `${x.fields.length} fields` })))}{group("Database", "db", model.prisma.models.map((x, i) => ({ href: `database/${i}`, label: x.name, meta: `${x.fields.length} fields` })))}<details open><summary><Icon name="grid"/>ER図</summary><button className={route === "er" ? "selected" : ""} onClick={() => open("er")}><strong>ER図</strong><small>Prismaリレーション</small></button></details><div className="explorer-resizer" onPointerDown={onResizeStart} role="separator" aria-label="Explorerの幅を変更"/></aside>; }
function Tabs({ pane, open, close, beginDrag, endDrag }) { return <div className="editor-tabs">{pane.tabs.map((tab) => <div className={tab === pane.active ? "editor-tab active" : "editor-tab"} draggable onDragStart={(event) => beginDrag(event, tab)} onDragEnd={endDrag} key={tab}><button title={titleOf(tab)} onClick={() => open(tab)}>{titleOf(tab)}</button>{tab !== "overview" && <button className="close-tab" aria-label={`${titleOf(tab)}を閉じる`} onClick={(event) => { event.stopPropagation(); close(tab); }}>×</button>}</div>)}</div>; }
function App() {
  const [route, setRoute] = useState(decodeURIComponent(location.hash.slice(1) || "overview"));
  const [panes, setPanes] = useState([{ id: 0, tabs: ["overview"], active: "overview" }]);
  const [activePane, setActivePane] = useState(0);
  const [split, setSplit] = useState("none");
  const [dragging, setDragging] = useState(null);
  const [dropTarget, setDropTarget] = useState(null);
  const [explorerOpen, setExplorerOpen] = useState(() => window.localStorage.getItem("specdock:explorer") !== "closed");
  const [explorerWidth, setExplorerWidth] = useState(240);
  const [resizingExplorer, setResizingExplorer] = useState(false);
  useEffect(() => { const listener = () => setRoute(decodeURIComponent(location.hash.slice(1) || "overview")); addEventListener("hashchange", listener); return () => removeEventListener("hashchange", listener); }, []);
  useEffect(() => { if (!resizingExplorer) return undefined; const move = (event) => setExplorerWidth(Math.min(420, Math.max(160, event.clientX - 44))); const stop = () => setResizingExplorer(false); window.addEventListener("pointermove", move); window.addEventListener("pointerup", stop, { once: true }); return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", stop); }; }, [resizingExplorer]);
  const selectPane = (paneIndex) => { setActivePane(paneIndex); const next = panes[paneIndex]?.active || "overview"; setRoute(next); location.hash = next; };
  const open = (next, paneIndex = activePane) => { setPanes((items) => items.map((pane, index) => index === paneIndex ? { ...pane, tabs: pane.tabs.includes(next) ? pane.tabs : [...pane.tabs, next], active: next } : pane)); setActivePane(paneIndex); setRoute(next); location.hash = next; };
  const close = (tab, paneIndex = activePane) => { if (tab === "overview") return; const pane = panes[paneIndex]; const tabs = pane.tabs.filter((item) => item !== tab); const next = pane.active === tab ? tabs[tabs.length - 1] : pane.active; if (!tabs.length && panes.length > 1) { setPanes((items) => items.filter((_, index) => index !== paneIndex)); setSplit("none"); const nextPane = paneIndex === 0 ? 0 : paneIndex - 1; setActivePane(nextPane); setRoute(panes[nextPane]?.active || "overview"); location.hash = panes[nextPane]?.active || "overview"; return; } setPanes((items) => items.map((item, index) => index === paneIndex ? { ...item, tabs, active: next } : item)); if (paneIndex === activePane && pane.active === tab) { setRoute(next); location.hash = next; } };
  const moveTab = (tab, from, to) => { if (from === to) { open(tab, to); return; } const sourceWillClose = panes.length > 1 && panes[from]?.tabs.length === 1; const targetIndex = sourceWillClose && from < to ? to - 1 : to; setPanes((items) => { const next = items.map((pane) => ({ ...pane, tabs: [...pane.tabs] })); const source = next[from]; if (!source) return items; source.tabs = source.tabs.filter((item) => item !== tab); source.active = source.active === tab ? source.tabs[source.tabs.length - 1] : source.active; if (!source.tabs.length && next.length > 1) next.splice(from, 1); const target = next[targetIndex]; if (!target) return next; if (!target.tabs.includes(tab)) target.tabs.push(tab); target.active = tab; return next; }); const nextPane = sourceWillClose ? targetIndex : to; setSplit(sourceWillClose ? "none" : "horizontal"); setActivePane(nextPane); setRoute(tab); location.hash = tab; };
  const beginDrag = (event, tab, source = activePane) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", tab); setDragging({ tab, source }); };
  const updateDropTarget = (event, paneIndex) => { event.preventDefault(); if (!dragging) return; const rect = event.currentTarget.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width; const edge = x < .2 ? "left" : x > .8 ? "right" : null; setDropTarget(edge ? { pane: paneIndex, edge } : null); };
  const dropTab = (event, target) => { event.preventDefault(); const data = event.dataTransfer.getData("text/plain"); const drag = dragging || { tab: data, source: activePane }; if (!drag?.tab) return; const rect = event.currentTarget.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width; const edge = x < .2 || x > .8; if (edge && panes.length === 1) { setPanes((items) => items.map((pane, index) => { if (index !== drag.source || drag.tab === "overview") return pane; const tabs = pane.tabs.filter((item) => item !== drag.tab); return { ...pane, tabs: tabs.length ? tabs : ["overview"], active: pane.active === drag.tab ? (tabs[tabs.length - 1] || "overview") : pane.active }; }).concat({ id: 1, tabs: [drag.tab], active: drag.tab })); setSplit("horizontal"); setActivePane(1); setRoute(drag.tab); location.hash = drag.tab; } else moveTab(drag.tab, drag.source, target); setDragging(null); setDropTarget(null); };
  const renderPage = (target, paneIndex) => { const { view, id } = parseRoute(target); const paneOpen = (next) => open(next, paneIndex); if (view === "overview") return <Overview open={paneOpen}/>; if (view === "api") return <ApiPage id={id}/>; if (view === "database") return <DatabasePage id={id}/>; if (view === "zod") return <ZodPage id={id}/>; if (view === "document") return <DocumentPage id={id} open={paneOpen}/>; if (view === "er") return <ErPage/>; return <Overview open={paneOpen}/>; };
  const toggleExplorer = () => setExplorerOpen((value) => { const next = !value; window.localStorage.setItem("specdock:explorer", next ? "open" : "closed"); return next; });
  return <div className={`shell ${resizingExplorer ? "resizing-explorer" : ""} ${explorerOpen ? "" : "explorer-collapsed"}`} style={{ gridTemplateColumns: `44px ${explorerOpen ? explorerWidth : 0}px minmax(0, 1fr)` }}><ActivityRail route={route} open={open} toggleExplorer={toggleExplorer} explorerOpen={explorerOpen}/>{explorerOpen && <Explorer route={route} open={open} onClose={toggleExplorer} onResizeStart={(event) => { event.preventDefault(); setResizingExplorer(true); }}/>}<main className="workspace"><div className={`editor-panes ${split !== "none" ? `split-${split}` : ""}`}>{panes.map((pane, index) => { const target = dropTarget?.pane === index ? dropTarget.edge : ""; return <section className={`${index === activePane ? "editor-pane active" : "editor-pane"} ${target ? `drop-${target}` : ""}`} onClick={() => selectPane(index)} onDragOver={(event) => updateDropTarget(event, index)} onDragLeave={() => setDropTarget(null)} onDrop={(event) => dropTab(event, index)} key={pane.id}><div className="pane-tabs"><Tabs pane={pane} open={(next) => open(next, index)} close={(tab) => close(tab, index)} beginDrag={(event, tab) => beginDrag(event, tab, index)} endDrag={() => { setDragging(null); setDropTarget(null); }}/><span className="drop-hint">左右の端へドロップして分割</span></div><div className="pane-content">{renderPage(pane.active, index)}</div></section>; })}</div></main></div>;
}
createRoot(document.getElementById("root")).render(<App/>);
